-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `folders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `folders` ;

CREATE TABLE IF NOT EXISTS `folders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `files` ;

CREATE TABLE IF NOT EXISTS `files` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `folder_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE,
  INDEX `fk_files_folders_idx` (`folder_id` ASC) VISIBLE,
  CONSTRAINT `FK_files_folders`
    FOREIGN KEY (`folder_id`)
    REFERENCES `folders` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permissions` ;

CREATE TABLE IF NOT EXISTS `permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `permission_type` VARCHAR(45) NULL,
  `folder_id` BIGINT NOT NULL,
  `expires_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `folder_id`, `user_id`),
  INDEX `FK_permissions_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_permissions_folders_idx` (`folder_id` ASC) VISIBLE,
  CONSTRAINT `FK_permissions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_permissions_folders`
    FOREIGN KEY (`folder_id`)
    REFERENCES `folders` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `temporary_links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `temporary_links` ;

CREATE TABLE IF NOT EXISTS `temporary_links` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `folder_id` BIGINT NOT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `FK_temporary_files_idx` (`folder_id` ASC) VISIBLE,
  CONSTRAINT `FK_temporary_folders`
    FOREIGN KEY (`folder_id`)
    REFERENCES `folders` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `temporary_links`
ADD COLUMN `upload_token` VARCHAR(60) UNIQUE NULL AFTER `email`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT * FROM users;

DELETE FROM users
WHERE id = 4;

UPDATE users
SET user_type = 'client'
WHERE id = 6;

SELECT * FROM folders;

INSERT INTO folders (name, created_at, updated_at)
VALUES
    ('Laravel Projects', NOW(), NOW()),
    ('JavaScript Projects',  NOW(), NOW()),
    ('Other Resources', NOW(), NOW());
    
DELETE FROM folders
WHERE id IN (1, 2, 3);

ALTER TABLE folders
DROP COLUMN user_id;

ALTER TABLE folders
DROP FOREIGN KEY FK_folders_users;

INSERT INTO permissions (user_id, folder_id, permission_type)
VALUES (1, 5, 'read'); -- El usuario 1 tiene permiso de lectura en la carpeta 5

-- Insertar el primer archivo
INSERT INTO files (folder_id, name, path, size, mime_type, created_at, updated_at) VALUES
(1, 'documento1.txt', 'uploads/documento1.txt', 150, 'text/plain', NOW(), NOW());

-- Insertar el segundo archivo
INSERT INTO files (folder_id, name, path, size, mime_type, created_at, updated_at) VALUES
(1, 'imagen1.jpg', 'uploads/imagen1.jpg', 120000, 'image/jpeg', NOW(), NOW());

-- Insertar el tercer archivo en otra carpeta
INSERT INTO files (folder_id, name, path, size, mime_type, created_at, updated_at) VALUES
(3, 'presentacion.pdf', 'uploads/presentacion.pdf', 550000, 'application/pdf', NOW(), NOW());

-- Insertar un cuarto archivo
INSERT INTO files (folder_id, name, path, size, mime_type, created_at, updated_at) VALUES
(2, 'hoja_calculo.xlsx', 'uploads/hoja_calculo.xlsx', 210000, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', NOW(), NOW());

-- Puedes añadir más sentencias INSERT INTO según la cantidad de archivos que quieras insertar

-- Ejemplo de otro archivo
INSERT INTO files (folder_id, name, path, size, mime_type, created_at, updated_at) VALUES
(1, 'otro_documento.txt', 'uploads/otro_documento.txt', 200, 'text/plain', NOW(), NOW());